---
- name: Extract kafka 
  unarchive:
    src: "{{ kafka_url }}"
    dest: "{{ kafka_path }}"
    remote_src: yes

- name: Run zookeeper
  command: "{{ kafka_path }}"/bin/zookeeper-server-start.sh /opt/kafka/config/zookeeper.properties

- name: Run kafka
  command: "{{ kafka_path }}"/bin/kafka-server-start.sh /opt/kafka/config/server.properties
