---
- name: Create /opt dir
  file:
    path: /opt
    state: directory

- name: Extract kafka 
  unarchive:
    src: "{{ kafka_url }}"
    dest: /opt
    remote_src: yes

- name: Run zookeeper
  shell: "/opt/kafka_2.11-1.0.0/bin/zookeeper-server-start.sh /opt/kafka_2.11-1.0.0/config/zookeeper.properties&"

- name: Run kafka
  shell: "/opt/kafka_2.11-1.0.0/bin/kafka-server-start.sh /opt/kafka_2.11-1.0.0/config/server.properties &"
